import { TemplateType } from '@/src/lib/types/editor';

const TEMPLATE_DEFAULTS: Record<TemplateType, Record<string, string>> = {
  hero: {
    title: 'Welcome to Your Page',
    description: 'A beautiful hero section to capture attention and deliver your key message with impact.',
    primaryButton: 'Get Started',
    secondaryButton: 'Learn More',
  },
  accordion: {
    title: 'Accordion Section',
    item1Title: 'Section One',
    item1Content: 'Content for the first section. Add your detailed information here.',
    item2Title: 'Section Two',
    item2Content: 'Content for the second section. Add your detailed information here.',
    item3Title: 'Section Three',
    item3Content: 'Content for the third section. Add your detailed information here.',
  },
  card: {
    title: 'Card Title',
    content: 'Add your content here. This card component is perfect for highlighting important information.',
    linkText: 'Learn more',
  },
  cta: {
    title: 'Ready to Get Started?',
    description: 'Join thousands of satisfied customers today.',
    primaryButton: 'Start Free Trial',
    secondaryButton: 'View Demo',
  },
  testimonial: {
    quote: 'This product has completely transformed how we work. The attention to detail is outstanding.',
    author: 'John Doe',
    position: 'CEO at TechCorp',
    initials: 'JD',
  },
  twoColumn: {
    leftTitle: 'Left Column',
    leftContent: 'Add your content in the left column. Perfect for side-by-side comparisons.',
    rightTitle: 'Right Column',
    rightContent: 'Add your content in the right column.',
  },
  threeColumn: {
    col1Title: 'First',
    col1Description: 'Description for the first column.',
    col2Title: 'Second',
    col2Description: 'Description for the second column.',
    col3Title: 'Third',
    col3Description: 'Description for the third column.',
  },
  gridLayout: {
    feature1Title: 'Feature One',
    feature2Title: 'Feature Two',
    feature3Title: 'Feature Three',
    feature4Title: 'Feature Four',
    featureDescription: 'Brief description of this feature.',
  },
  sidebarLayout: {
    sidebarTitle: 'Sidebar',
    sidebarItem1: 'Item One',
    sidebarItem2: 'Item Two',
    sidebarItem3: 'Item Three',
    mainTitle: 'Main Content',
    mainContent: 'Your main content goes here.',
  },
  features: {
    sectionTitle: 'Features',
    sectionSubtitle: 'Everything you need to succeed',
    feature1Title: 'Lightning Fast',
    feature1Description: 'Optimized for speed and performance.',
    feature2Title: 'Beautiful Design',
    feature2Description: 'Carefully crafted interfaces.',
    feature3Title: 'Secure & Reliable',
    feature3Description: 'Built with security first.',
  },
  pricing: {
    sectionTitle: 'Simple Pricing',
    sectionSubtitle: "Choose the plan that's right for you",
    plan1Name: 'Starter',
    plan1Price: '$9',
    plan2Name: 'Pro',
    plan2Price: '$29',
    plan2Badge: 'POPULAR',
    plan3Name: 'Enterprise',
    plan3Price: '$99',
    planFeature1: 'Feature one',
    planFeature2: 'Feature two',
    planFeature3: 'Feature three',
    planFeature4: 'Everything in Starter',
    planFeature5: 'Advanced features',
    planFeature6: 'Priority support',
    planFeature7: 'Everything in Pro',
    planFeature8: 'Custom solutions',
    planFeature9: 'Dedicated support',
    ctaText: 'Get Started',
    ctaAltText: 'Contact Sales',
  },
  faq: {
    title: 'Frequently Asked Questions',
    question1: 'How does it work?',
    answer1: "Our solution is designed to be intuitive and easy to use. Simply sign up and you're ready to go.",
    question2: "What's included in the plan?",
    answer2: 'Each plan includes access to all core features, with higher tiers offering additional benefits.',
    question3: 'Can I cancel anytime?',
    answer3: 'Yes! You can cancel your subscription at any time with no hidden fees.',
  },
  timeline: {
    title: 'Our Journey',
    event1Year: '2020',
    event1Title: 'Company Founded',
    event1Description: 'Started with a vision to revolutionize the industry.',
    event2Year: '2022',
    event2Title: 'Major Milestone',
    event2Description: 'Reached 100,000 satisfied customers worldwide.',
    event3Year: '2024',
    event3Title: 'New Chapter',
    event3Description: 'Launched next-generation platform with AI capabilities.',
  },
  stats: {
    title: 'By the Numbers',
    stat1Value: '10K+',
    stat1Label: 'Active Users',
    stat2Value: '98%',
    stat2Label: 'Satisfaction Rate',
    stat3Value: '50+',
    stat3Label: 'Countries',
    stat4Value: '24/7',
    stat4Label: 'Support',
  },
  team: {
    title: 'Meet Our Team',
    subtitle: 'The people behind our success',
    member1Initials: 'AS',
    member1Name: 'Alex Smith',
    member1Role: 'CEO & Founder',
    member1Bio: 'Passionate about building products that make a difference.',
    member2Initials: 'SJ',
    member2Name: 'Sarah Johnson',
    member2Role: 'Head of Design',
    member2Bio: 'Creating beautiful experiences that users love.',
    member3Initials: 'MC',
    member3Name: 'Mike Chen',
    member3Role: 'CTO',
    member3Bio: 'Building scalable systems with cutting-edge technology.',
  },
  newsletter: {
    title: 'Stay Updated',
    description: 'Subscribe to our newsletter for the latest updates.',
    inputPlaceholder: 'your@email.com',
    buttonLabel: 'Subscribe',
    footerNote: 'We respect your privacy. Unsubscribe anytime.',
  },
  'callout-info': {
    title: 'Information',
    content: 'This is an informational callout. Use it to highlight helpful information.',
  },
  'callout-warning': {
    title: 'Warning',
    content: 'This is a warning callout. Use it to draw attention to important considerations.',
  },
  'callout-success': {
    title: 'Success',
    content: 'This is a success callout. Use it to confirm positive outcomes.',
  },
  'callout-error': {
    title: 'Error',
    content: 'This is an error callout. Use it to highlight critical issues.',
  },
  'callout-tip': {
    title: 'Pro Tip',
    content: 'This is a tip callout. Use it to share helpful hints and best practices.',
  },
  checkList: {
    title: 'Checklist',
    item1: 'First item completed',
    item2: 'Second item completed',
    item3: 'Third item pending',
  },
  stepList: {
    title: 'Step-by-Step Guide',
    step1Title: 'First Step',
    step1Description: 'Description of the first step in the process.',
    step2Title: 'Second Step',
    step2Description: 'Description of the second step in the process.',
    step3Title: 'Third Step',
    step3Description: 'Description of the third step in the process.',
  },
  iconList: {
    title: 'Key Features',
    item1Title: 'Feature One',
    item2Title: 'Feature Two',
    item3Title: 'Feature Three',
    itemDescription: 'Brief description of this feature.',
  },
  comparisonTable: {
    title: 'Feature Comparison',
    headerFeature: 'Feature',
    headerBasic: 'Basic',
    headerPro: 'Pro',
    headerEnterprise: 'Enterprise',
    row1Feature: 'Feature One',
    row2Feature: 'Feature Two',
    row3Feature: 'Feature Three',
  },
};

export const getTemplateDefaults = (type: TemplateType): Record<string, string> => {
  return TEMPLATE_DEFAULTS[type] || {};
};
